services:
  similar-strings:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PRODUCTION: "ON"
        BUILD_TYPE: "Release"
    container_name: similar_strings_app
    ports:
      - "8000:8000"
