services:
  gutsy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gutsy_app
    ports:
      - "8000:8000"
    volumes:
      - ./words_clean.txt:/app/words_clean.txt
    command: ["/app/Gutsy", "/app/words_clean.txt"]
