name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test if GHCR_PAT is Set Correctly
        run: |
          if [ -z "${{ secrets.GHCR_PAT }}" ]; then
            echo "❌ GHCR_PAT is missing or not set properly!"
            exit 1
          else
            echo "✅ GHCR_PAT is set correctly."
          fi

      - name: Test GHCR Authentication
        run: |
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          if [ $? -eq 0 ]; then
            echo "✅ Successfully authenticated to GHCR!"
          else
            echo "❌ Authentication to GHCR failed! Check your PAT permissions."
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/katzirgal/similar-strings-runtime:latest .
          docker push ghcr.io/katzirgal/similar-strings-runtime:latest
